language: node_js
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 15
  - yarn
script:
  - yarn run prettier
  - yarn run lint
  - yarn test
after_success:
  - 'yarn run test:coverage'
