language: node_js
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 15
  - npm install
script:
  - npm run prettier
  - npm run lint
  - npm test
after_success:
  - 'npm run test:coverage'
